# Refresh ALL scripts on adv update
name: Observation (Full)

on:
  release:
    types:
      # Only catch released versions
      - released
  workflow_dispatch:
    inputs:
      revision:
        description: "Octo revision"
        required: false
        default: "none"
        type: string
      forced:
        description: "Forced regenerate"
        required: false
        default: false
        type: boolean
      skipAdv:
        description: "Skip adv update"
        required: false
        default: false
        type: boolean
      skipSud:
        description: "Skip sud update"
        required: false
        default: false
        type: boolean
      skipSpi:
        description: "Skip spi update"
        required: false
        default: false
        type: boolean

jobs:
  adv_observe_full:
    if: inputs.skipAdv != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19 # cuz we need Fetch API
      - name: Build package
        run: |
          npx pnpm@8 install
          npx pnpm@8 install @aws-sdk/client-s3@3.354.0
          npm run build
      - name: Update all items
        run: node observer/full.mjs
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          ASSETS_BUCKET_NAME: ${{ secrets.ASSETS_BUCKET_NAME }}
          BACKEND_MANAGE_READ_KEY: ${{ secrets.BACKEND_MANAGE_READ_KEY }}
          BACKEND_MANAGE_WRITE_KEY: ${{ secrets.BACKEND_MANAGE_WRITE_KEY }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_REGION: ${{ secrets.S3_REGION }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          UPSTREAM_BASE_DOMAIN: ${{ secrets.UPSTREAM_BASE_DOMAIN }}
          OCTO_REVISION: ${{ inputs.revision }}
          FORCED: ${{ inputs.forced }}

  sud_observe_full:
    if: inputs.skipSud != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "outloudvi/idoly-assets-curator"
          ref: "observer"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install dependencies
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
          bash install.sh
          pipenv install
      - run: pipenv run python observe_sud.py
        env:
          B2_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          B2_APP_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          B2_BUCKET_NAME: ${{ secrets.ASSETS_BUCKET_NAME }}
          B2_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT }}
          B2_REGION: ${{ secrets.S3_REGION }}
          API_SECRET: ${{ secrets.BACKEND_MANAGE_READ_KEY }}
          UPSTREAM_BASE_DOMAIN: ${{ secrets.UPSTREAM_BASE_DOMAIN }}
          OCTO_REVISION: ${{ inputs.revision }}
          FORCED: ${{ inputs.forced }}

  spi_observe_full:
    if: inputs.skipSpi != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "outloudvi/idoly-assets-curator"
          ref: "observer"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install dependencies
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
          bash install.sh
          pipenv install
      - run: pipenv run python observe_spi.py
        env:
          B2_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          B2_APP_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          B2_BUCKET_NAME: ${{ secrets.ASSETS_BUCKET_NAME }}
          B2_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT }}
          B2_REGION: ${{ secrets.S3_REGION }}
          API_SECRET: ${{ secrets.BACKEND_MANAGE_READ_KEY }}
          UPSTREAM_BASE_DOMAIN: ${{ secrets.UPSTREAM_BASE_DOMAIN }}
          OCTO_REVISION: ${{ inputs.revision }}
          FORCED: ${{ inputs.forced }}
